# .rubocop.yml
# これは RuboCop の基本ルールを定義するファイルです。
# プロジェクト全体でコードスタイルを統一するために使います。

# auto-gen-config で生成された .rubocop_todo.yml を読み込む
# → まだ直せてない違反を一時的に無視できる
inherit_from:
  - .rubocop_todo.yml

AllCops:
  # 新しい Cop が RuboCop に追加されたとき、自動で有効にするか
  # → 常に最新ルールを適用したいので enable
  NewCops: enable

  # Ruby のバージョンを指定（Gemfile の "ruby '3.2.3'" に合わせる）
  TargetRubyVersion: 3.2

  # RuboCop の対象外にするファイルやフォルダ
  Exclude:
    - 'bin/**/*'          # Rails が生成する bin ファイル
    - 'db/schema.rb'      # 自動生成される DB スキーマ
    - 'node_modules/**/*' # JS の依存パッケージ
    - 'vendor/**/*'       # gem を vendor/bundle に入れる場合
    - 'log/**/*'
    - 'tmp/**/*'

# 行の長さに関するルール
Layout/LineLength:
  Max: 120              # デフォルト80は厳しいので120文字に緩和
  Exclude:
    - 'spec/**/*'       # テストコードは長くなりがちなので除外

# ブロックが長すぎると怒られるルール
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'       # RSpec の describe/context は長くなるので除外

# frozen_string_literal コメントを必須にするか
Style/FrozenStringLiteralComment:
  Enabled: false        # Ruby3では不要なのでオフ

# 改行コードの統一
Layout/EndOfLine:
  EnforcedStyle: lf     # Windows の CRLF を強制的に LF に統一
