default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: "user"
  host: localhost
  port: 3306
  # ↓ ローカルでは SSL 使わない（証明書が無いので）
  # sslverify: false

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  # 本番は別設定を使う想定。ENVから上書きするなど。
  # username: app
  # password: <%= ENV['APP_DATABASE_PASSWORD'] %>
